Repository OpenVoiceOS/ovos-lingua-franca, pull requests merged in 2022-04, with the labels that each got.

#10 fix MycroftAI/lingua-franca/issues/20
  lingua_franca/lang/parse_en.py
  test/unittests/test_parse_en.py
Labels: bug

#4 port/azerbeijan
  lingua_franca/internal.py
  lingua_franca/lang/common_data_az.py
  lingua_franca/lang/format_az.py
  lingua_franca/lang/parse_az.py
  lingua_franca/res/text/az-az/and.word
  lingua_franca/res/text/az-az/date_time.json
  lingua_franca/res/text/az-az/date_time_test.json
  lingua_franca/res/text/az-az/day.word
  lingua_franca/res/text/az-az/days.word
  lingua_franca/res/text/az-az/hour.word
  lingua_franca/res/text/az-az/hours.word
  lingua_franca/res/text/az-az/minute.word
  lingua_franca/res/text/az-az/minutes.word
  lingua_franca/res/text/az-az/normalize.json
  lingua_franca/res/text/az-az/or.word
  lingua_franca/res/text/az-az/second.word
  lingua_franca/res/text/az-az/seconds.word
  test/test_format_az.py
  test/test_parse_az.py
Labels: enhancement, new language

#11 fix MycroftAI/lingua-franca/issues/59 + 225
  lingua_franca/lang/parse_en.py
  test/unittests/test_parse_en.py
Labels: bug

#5 feat/langcode_utils
  .github/workflows/license_tests.yml
  lingua_franca/format.py
  lingua_franca/parse.py
  lingua_franca/res/text/en-us/langs.json
  lingua_franca/util.py
  requirements/requirements.txt
  test/license_tests.py
  test/unittests/test_format_az.py
  test/unittests/test_format_en.py
  test/unittests/test_parse.py
  test/unittests/test_parse_az.py
  test/unittests/test_parse_en.py
Labels: enhancement

#23 notify matrix chat on PR merged
  .github/workflows/notify_matrix.yml
Labels: automation
